// lib/onboarding/genre-albums.ts
import type { GenreKey } from "./genre-map";

export type CuratedAlbum = {
  artistName: string;
  albumName: string;
};

export const GENRE_ALBUMS: Record<GenreKey, CuratedAlbum[]> = {
  rock: [
    { artistName: "The Beatles", albumName: "Abbey Road" },
    { artistName: "Nirvana", albumName: "Nevermind" },
    { artistName: "Radiohead", albumName: "OK Computer" },
    { artistName: "Pink Floyd", albumName: "The Dark Side of the Moon" },
    { artistName: "Led Zeppelin", albumName: "Led Zeppelin IV" },
    { artistName: "Fleetwood Mac", albumName: "Rumours" },
    { artistName: "Bruce Springsteen", albumName: "Born to Run" },
    { artistName: "The Rolling Stones", albumName: "Exile on Main St." },
  ],
  indie: [
    { artistName: "Arcade Fire", albumName: "Funeral" },
    { artistName: "The Strokes", albumName: "Is This It" },
    { artistName: "Neutral Milk Hotel", albumName: "In the Aeroplane Over the Sea" },
    { artistName: "Bon Iver", albumName: "For Emma, Forever Ago" },
    { artistName: "Sufjan Stevens", albumName: "Illinois" },
    { artistName: "Car Seat Headrest", albumName: "Twin Fantasy" },
    { artistName: "Big Thief", albumName: "Dragon New Warm Mountain I Believe in You" },
    { artistName: "Japanese Breakfast", albumName: "Soft Sounds from Another Planet" },
  ],
  pop: [
    { artistName: "Michael Jackson", albumName: "Thriller" },
    { artistName: "Beyoncé", albumName: "Lemonade" },
    { artistName: "Taylor Swift", albumName: "1989" },
    { artistName: "Prince", albumName: "Purple Rain" },
    { artistName: "Dua Lipa", albumName: "Future Nostalgia" },
    { artistName: "Adele", albumName: "21" },
    { artistName: "Frank Ocean", albumName: "channel ORANGE" },
    { artistName: "Robyn", albumName: "Body Talk" },
  ],
  "hip-hop": [
    { artistName: "Nas", albumName: "Illmatic" },
    { artistName: "Kendrick Lamar", albumName: "To Pimp a Butterfly" },
    { artistName: "Kanye West", albumName: "My Beautiful Dark Twisted Fantasy" },
    { artistName: "Jay-Z", albumName: "The Blueprint" },
    { artistName: "Kendrick Lamar", albumName: "good kid, m.A.A.d city" },
    { artistName: "Kanye West", albumName: "The College Dropout" },
    { artistName: "OutKast", albumName: "Aquemini" },
    { artistName: "Notorious B.I.G.", albumName: "Ready to Die" },
  ],
  "rnb-soul": [
    { artistName: "Marvin Gaye", albumName: "What's Going On" },
    { artistName: "Stevie Wonder", albumName: "Songs in the Key of Life" },
    { artistName: "Amy Winehouse", albumName: "Back to Black" },
    { artistName: "Frank Ocean", albumName: "Blonde" },
    { artistName: "D'Angelo", albumName: "Voodoo" },
    { artistName: "SZA", albumName: "SOS" },
    { artistName: "Lauryn Hill", albumName: "The Miseducation of Lauryn Hill" },
    { artistName: "Solange", albumName: "A Seat at the Table" },
  ],
  electronic: [
    { artistName: "Daft Punk", albumName: "Discovery" },
    { artistName: "Aphex Twin", albumName: "Selected Ambient Works 85-92" },
    { artistName: "Boards of Canada", albumName: "Music Has the Right to Children" },
    { artistName: "Daft Punk", albumName: "Random Access Memories" },
    { artistName: "The Avalanches", albumName: "Since I Left You" },
    { artistName: "Four Tet", albumName: "There Is Love in You" },
    { artistName: "LCD Soundsystem", albumName: "Sound of Silver" },
    { artistName: "Bicep", albumName: "Bicep" },
  ],
  jazz: [
    { artistName: "Miles Davis", albumName: "Kind of Blue" },
    { artistName: "John Coltrane", albumName: "A Love Supreme" },
    { artistName: "Dave Brubeck", albumName: "Time Out" },
    { artistName: "Herbie Hancock", albumName: "Head Hunters" },
    { artistName: "Charles Mingus", albumName: "Mingus Ah Um" },
    { artistName: "Miles Davis", albumName: "Bitches Brew" },
    { artistName: "Bill Evans", albumName: "Waltz for Debby" },
    { artistName: "Thelonious Monk", albumName: "Brilliant Corners" },
  ],
  classical: [
    { artistName: "Johann Sebastian Bach", albumName: "Goldberg Variations" },
    { artistName: "Ludwig van Beethoven", albumName: "Symphony No. 9" },
    { artistName: "Antonio Vivaldi", albumName: "The Four Seasons" },
    { artistName: "Igor Stravinsky", albumName: "The Rite of Spring" },
    { artistName: "Claude Debussy", albumName: "Préludes" },
    { artistName: "Wolfgang Amadeus Mozart", albumName: "Requiem in D minor" },
  ],
  metal: [
    { artistName: "Metallica", albumName: "Master of Puppets" },
    { artistName: "Black Sabbath", albumName: "Paranoid" },
    { artistName: "Tool", albumName: "Lateralus" },
    { artistName: "Iron Maiden", albumName: "The Number of the Beast" },
    { artistName: "Slayer", albumName: "Reign in Blood" },
    { artistName: "Opeth", albumName: "Blackwater Park" },
    { artistName: "Pantera", albumName: "Vulgar Display of Power" },
    { artistName: "Mastodon", albumName: "Crack the Skye" },
  ],
  folk: [
    { artistName: "Bob Dylan", albumName: "Blood on the Tracks" },
    { artistName: "Joni Mitchell", albumName: "Blue" },
    { artistName: "Nick Drake", albumName: "Pink Moon" },
    { artistName: "Bob Dylan", albumName: "The Freewheelin' Bob Dylan" },
    { artistName: "Simon & Garfunkel", albumName: "The Sound of Silence" },
    { artistName: "Sufjan Stevens", albumName: "Carrie & Lowell" },
    { artistName: "Fleet Foxes", albumName: "Fleet Foxes" },
    { artistName: "Iron & Wine", albumName: "The Creek Drank the Cradle" },
  ],
  alternative: [
    { artistName: "Radiohead", albumName: "The Bends" },
    { artistName: "Pixies", albumName: "Doolittle" },
    { artistName: "My Bloody Valentine", albumName: "Loveless" },
    { artistName: "The Smashing Pumpkins", albumName: "Siamese Dream" },
    { artistName: "R.E.M.", albumName: "Murmur" },
    { artistName: "Pavement", albumName: "Slanted and Enchanted" },
    { artistName: "The Cure", albumName: "Disintegration" },
    { artistName: "Weezer", albumName: "Weezer (Blue Album)" },
  ],
  punk: [
    { artistName: "The Clash", albumName: "London Calling" },
    { artistName: "Sex Pistols", albumName: "Never Mind the Bollocks" },
    { artistName: "Ramones", albumName: "Ramones" },
    { artistName: "Bad Brains", albumName: "Bad Brains" },
    { artistName: "Black Flag", albumName: "Damaged" },
    { artistName: "The Misfits", albumName: "Walk Among Us" },
  ],
  funk: [
    { artistName: "Parliament", albumName: "Mothership Connection" },
    { artistName: "Sly & the Family Stone", albumName: "There's a Riot Goin' On" },
    { artistName: "Prince", albumName: "Sign 'O' the Times" },
    { artistName: "James Brown", albumName: "Live at the Apollo" },
    { artistName: "Herbie Hancock", albumName: "Head Hunters" },
    { artistName: "George Clinton", albumName: "Computer Games" },
  ],
  reggae: [
    { artistName: "Bob Marley & The Wailers", albumName: "Catch a Fire" },
    { artistName: "Bob Marley & The Wailers", albumName: "Exodus" },
    { artistName: "Toots and the Maytals", albumName: "Funky Kingston" },
    { artistName: "Lee Scratch Perry", albumName: "Super Ape" },
    { artistName: "Augustus Pablo", albumName: "King Tubby Meets Rockers Uptown" },
  ],
  latin: [
    { artistName: "Buena Vista Social Club", albumName: "Buena Vista Social Club" },
    { artistName: "Celia Cruz", albumName: "La Negra Tiene Tumbao" },
    { artistName: "Carlos Santana", albumName: "Abraxas" },
    { artistName: "Caetano Veloso", albumName: "Transa" },
    { artistName: "Silvio Rodríguez", albumName: "Días y Flores" },
  ],
  ambient: [
    { artistName: "Brian Eno", albumName: "Music for Airports" },
    { artistName: "Aphex Twin", albumName: "Selected Ambient Works Volume II" },
    { artistName: "Stars of the Lid", albumName: "And Their Refinement of the Decline" },
    { artistName: "Brian Eno", albumName: "Discreet Music" },
    { artistName: "Grouper", albumName: "Dragging a Dead Deer Up a Hill" },
    { artistName: "William Basinski", albumName: "Disintegration Loops" },
  ],
  experimental: [
    { artistName: "Captain Beefheart", albumName: "Trout Mask Replica" },
    { artistName: "Can", albumName: "Tago Mago" },
    { artistName: "Swans", albumName: "To Be Kind" },
    { artistName: "Scott Walker", albumName: "Tilt" },
    { artistName: "Arca", albumName: "Mutant" },
    { artistName: "Bjork", albumName: "Homogenic" },
  ],
  country: [
    { artistName: "Johnny Cash", albumName: "American Recordings" },
    { artistName: "Willie Nelson", albumName: "Red Headed Stranger" },
    { artistName: "Kacey Musgraves", albumName: "Golden Hour" },
    { artistName: "Gram Parsons", albumName: "Grievous Angel" },
    { artistName: "Emmylou Harris", albumName: "Pieces of the Sky" },
    { artistName: "Townes Van Zandt", albumName: "Live at the Old Quarter, Houston, Texas" },
  ],
};
